check50:
  checks:
    first:
      - run: g++ -o two two.cpp;./two
        stdin: 
          - 0
        stdout: 32
        exit: 0
    second:
      - run: g++ -o two two.cpp;./two
        stdin: 
          - 100
        stdout: 212
        exit: 0
    third:
      - run: g++ -o two two.cpp;./two
        stdin: 
          - 60.9
        stdout: 141.62
        exit: 0